### ISSUE TITLE
SIM8800 doesn't run from directory on HDD

### ISSUE THREAD

**Issue by bobbimanners** [option8/sim8800#1]
It seems `LOADER.SYSTEM` hard-codes the prefix of '/SIM8800' so the software can only be run from a floppy with than volume name.  It would be better if it looked in the current prefix first.  This should enable it to work from an Apple HDD partition.

**Comment by option8** [comment]
latest 2MG fixes this.

**Comment by bobbimanners** [comment]
Awesome - I will give it a whirl!!
